# Generated by Django 2.2.24 on 2026-08-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_details',
            new_name='department_details',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='department_name',
        ),
    ]
