# Generated by Django 2.2.24 on 2026-08-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20260804_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='expirence',
            new_name='experience',
        ),
    ]
