# Generated by Django 2.2.24 on 2026-08-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_details',
            new_name='parent_phone',
        ),
    ]
