# Generated by Django 2.2.24 on 2026-08-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=models.DateField(),
        ),
    ]
