# Generated by Django 2.2.24 on 2026-08-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
